[package]
name = "rpg"
version = "0.1.0"
authors = ["Quincy <jjq.quirky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.8.0"
